Stream based resumability improvements
mongodb/mongo-spark pull request #99
Opened 2023-06-21 16:44 UTC by rozza

* Added `change.stream.start.at.operation.time` to allow configurable start time for microbatch or continuous streams.
* Added `MongoOffsetStore` for automatic storing and retrieving MongoOffsets. Allowing resumability of streams. Uses the `checkpointLocation` stream configuration.

SPARK-378 SPARK-379

2023-06-27 02:42 UTC, stIncMale requested changes

2023-06-27 09:38 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoOffset.java
> +    }
We didn't store offsets previously or provide any resumabilty based on offsets. So there is no backwards incompatibility.

2023-06-27 09:41 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java
> +      new BsonTimestamp(-1, 0).getValue();
For streams there is no real startup mode - eg copy existing.  However, that is on the road map and reusing the parameters seems like a good idea.

2023-06-27 10:03 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoOffset.java
> +    }
Good point. 

So previously the offset wasn't used at all by the connector and there was no resumability support. As such I don't consider the change backwards compatibility breaking.

Why was version added? This brings the format inline with other connectors and sparks internal formats for resumable offsets.

2023-06-27 10:22 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java
> +  }
Ack - will review the Mongo Kafka formats and bring them inline.

2023-06-27 10:30 UTC, rozza commented on src/integrationTest/java/com/mongodb/spark/sql/connector/read/AbstractMongoStreamTest.java
> +            ReadConfig.PREFIX + ReadConfig.STREAM_START_AT_OPERATION_TIME_CONFIG,
Updated - its not needed.

2023-06-27 10:31 UTC, rozza commented on src/integrationTest/java/com/mongodb/spark/sql/connector/read/AbstractMongoStreamTest.java
> +            (msg, ds) -> assertEquals(20, ds.collectAsList().size(), msg)));
Thanks - updated to 20.

2023-06-27 10:45 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java
> +      out.write(offset.json().getBytes(StandardCharsets.UTF_8));
Good catch - noticed that Spark uses hflush() - so opted for that.

2023-06-27 10:50 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java
> +  private final Path path;
Done

2023-06-27 10:52 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousInputPartitionOffset.java
> +    return "MongoContinuousInputPartitionOffset{" + "offset=" + offset.json() + '}';
:face_exhaling: turns out `Offset` has it defined as needed.

2023-06-27 11:13 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoContinuousInputPartitionOffset.java
> +    return ((BsonTimestampOffset) offset).getBsonTimestamp();
Nice - done, changed the name slightly.

2023-06-27 11:13 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java
> +  }
No reason - updated.

2023-06-27 11:13 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoOffsetStore.java
> +    LOGGER.info("Initial offset: {}", offset.json());
Done

2023-06-27 15:50 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/MongoOffset.java
> +    }
I have added legacy offset support.

2023-06-27 15:51 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java
> +      new BsonTimestamp(-1, 0).getValue();
Updated

2023-06-27 15:52 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/BsonTimestampOffset.java
Updated to match Kafka configs and copied across the BsonTimestampParser class for better human support.

2023-07-06 21:16 UTC, stIncMale requested changes
We are almost there, just a few small concerns.

2023-07-06 21:16 UTC, stIncMale commented on src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java
> +   * <p>Actuated only if 'startup.mode = timestamp'. Specifies the starting point for the change
```suggestion
   * <p>Actuated only if 'change.stream.startup.mode = timestamp'. Specifies the starting point for the change
```

2023-07-06 21:16 UTC, stIncMale commented on src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java
> +   * data, or may at first copy all existing source data and then continue with processing new data.
The Kafka Connector can do this, but there is no `StreamingStartupMode.COPY_EXISTING` in the Spark Connector. We should say something like the following:

```suggestion
   * the offset. If no offset is available, the connector may either ignore all existing data, or may read an offset from the configuration.
```

2023-07-07 10:18 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/BsonTimestampOffset.java
> +  }
Done

2023-07-07 10:18 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/BsonTimestampOffset.java
> +    return docJson.substring(6, docJson.length() - 1);
Done

2023-07-07 10:27 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/config/ReadConfig.java
> +  }
Sounds good

2023-07-07 13:31 UTC, rozza commented on src/main/java/com/mongodb/spark/sql/connector/read/BsonTimestampOffset.java
>    }
Synchronized the method to protect it.

2023-07-07 17:19 UTC, stIncMale approved these changes

2023-07-10 09:50 UTC, rozza commented
Manually rebased and merged.

2023-07-10 09:50 UTC, closed without merging